apiVersion: v1
kind: Service

metadata:
  name: enterprise-devops-service
  labels:
    app: enterprise-devops-app

spec:
  selector:
    app: enterprise-devops-app

  type: {{ .Values.service.type }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}