apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: enterprise-devops-servicemonitor
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: enterprise-devops-app

  endpoints:
    - port: http
      path: /metrics
      interval: 15s