apiVersion: v1
kind: Service

metadata:
  name: enterprise-devops-service

spec:
  selector:
    app: enterprise-devops-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort